# Generated by Django 4.0.4 on 2022-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='tweets.topic'),
        ),
    ]
